id: PBFE6909C
initial_creation_type: input
source_metadata:
  title: 'MSV 1,08: Kaṭhinavastu'
  language: bo
  volumes:
    ebb5d74f147241638ab128334ff74a9f:
      title: Kaṭhinavastu
      base_file: Kaṭhinavastu.txt
      work_id: W07A25652
  chapter_to_tile: {}
created_at: '2022-03-01T22:18:19.635978'
last_modified_at: '2022-03-01T22:18:19.635984'
